services:
#    family_health_member.example:
#        class: FamilyHealth\MemberBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    family_health_member.generate_member_id:
        class: FamilyHealth\MemberBundle\Job\MemberIdGenerator
        arguments: [ @doctrine.orm.entity_manager ]
